# Generated by Django 3.1.2 on 2020-11-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_auto_20201025_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
