# Generated by Django 3.1.3 on 2020-12-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='extension',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='upload',
            name='size',
            field=models.CharField(default='', max_length=15),
        ),
    ]
