# Generated by Django 3.1.3 on 2020-11-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='link',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
