# Generated by Django 3.1.3 on 2020-11-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default='files/None/No-doc.pdf', upload_to='files/'),
        ),
    ]
