# Generated by Django 3.1.3 on 2020-11-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThematicPages', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='thematic_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThematicPages.thematicpage'),
        ),
        migrations.DeleteModel(
            name='ThematicPage',
        ),
    ]
