# Generated by Django 3.1.3 on 2020-11-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thematic_pages', '0002_auto_20201120_2107'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='thematic_page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='thematic_pages.thematicpage'),
        ),
    ]
