# Generated by Django 3.1.3 on 2020-11-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, default='files/None/No-doc.pdf', null=True, upload_to='files/'),
        ),
    ]
