# Generated by Django 3.1.3 on 2020-12-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20201226_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='size',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
