# Generated by Django 3.1.3 on 2020-11-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20201120_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
