# Generated by Django 3.1.3 on 2020-12-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20201226_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='extension',
            new_name='name',
        ),
    ]
