# Generated by Django 2.2.16 on 2020-10-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_document_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='author',
            new_name='Uploader',
        ),
        migrations.AddField(
            model_name='document',
            name='Title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
