# Generated by Django 2.2.16 on 2020-10-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201021_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Uploader',
            new_name='uploader',
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
