# Generated by Django 3.1.3 on 2020-11-20 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('moderators', models.ManyToManyField(blank=True, default=None, null=True, related_name='can_moderate', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ManyToManyField(blank=True, default=None, null=True, related_name='requested_pages', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, default=None, null=True, related_name='can_view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
