# Generated by Django 3.1.2 on 2020-10-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_auto_20201021_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='tag',
            new_name='tags',
        ),
    ]
