# Generated by Django 3.1.3 on 2020-11-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mid_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('0', 'administrator'), ('1', 'moderators'), ('2', 'regular')], default='2', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
