# Generated by Django 3.1.3 on 2020-11-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Not Student')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.IntegerField(choices=[(0, 'Bachelor'), (1, 'Master'), (2, 'Not Student')], default=0),
        ),
    ]
