# Generated by Django 3.1.3 on 2020-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.IntegerField(choices=[(0, 'Bs'), (1, 'Ms')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.IntegerField(choices=[(0, 'Cs'), (1, 'Rb'), (2, 'Ds'), (3, 'Se'), (4, 'Sne'), (5, 'Notiu')], default=0),
        ),
    ]
