# Generated by Django 3.1.3 on 2020-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201119_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.IntegerField(choices=[(0, 'Bachelor'), (1, 'Master')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='track',
            field=models.IntegerField(choices=[(0, 'Computer Science'), (1, 'Robotics'), (2, 'Data Science'), (3, 'Software Engineering'), (4, 'Security'), (5, 'Not Student')], default=0),
        ),
    ]
