# Generated by Django 3.1.3 on 2020-11-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mid_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
