# Generated by Django 3.1.3 on 2020-11-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201118_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'administrator'), ('1', 'moderator'), ('2', 'regular')], default='2', max_length=1),
        ),
    ]
