# Generated by Django 3.1.2 on 2020-11-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0005_auto_20201114_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
