# Generated by Django 3.1.2 on 2020-11-19 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Storage', '0009_auto_20201119_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content2', models.TextField()),
                ('date_posted2', models.DateTimeField(default=django.utils.timezone.now)),
                ('author2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_connected2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments2', to='Storage.upload')),
            ],
        ),
    ]
